### ISSUE TITLE
Synergize crashes when adding more than one voice to newly created cart

### ISSUE THREAD

**Issue by tyhodson** [chinenual/synergize#82]
Hi. Thank you for your work on this -- it's really well done!

---

Issue:

I can add one voice to a new cart that I called TEST.CRT, but when I try to add a second voice, the app crashes. I can delete the voice in slot number 1 and then add a different voice to slot 1, but I can't add voices to any other slots.

- Mac OS 14.4.1
- Mac Mini M2

Steps to reproduce:

- Open Synergize (SynergyVoiceLibrary is already loaded)
- In Library mode, click on CARTS
- Click on custom cart called TEST (which has one voice in slot 1 only)
- Press Edit CRT, and then press OK to connect to Synergia app
- Click + next to slot 2 (or any other slot besides slot 1)
- Choose any VCE file and press Open
- (Synergize crashes)

Note -- While re-testing this I found that if I edited an existing (fully populated) cart and saved it as a new cart, I could manipulate any of the voice slots. To verify the issue above wasn't a corrupt cart, I edited an existing cart and removed all but one voice and saved it as a new cart. When I opened the new cart (with one voice), I ran into the problem described above when trying to add a second voice.

So even though I found a workaround, since the issue is easily reproducible, I figured I'd report it.

-------------

Log output below:

2024/06/15 15:30:15 INFO: Running app version 2.6.1 (20240522)
2024/06/15 15:30:15 INFO: Operating environment: goInfo.GoInfoObject{GoOS:"darwin", Kernel:"Darwin", Core:"23.4.0", Platform:"x86_64", OS:"Darwin", Hostname:"earthlight.local", CPUs:8}
2024/06/15 15:30:15 INFO: Default serial device is /dev/tty.usbserial-m0000855 at 9600 baud
2024/06/15 15:30:15 INFO: astikit: starting worker...
2024/06/15 15:30:18 INFO: url: https://api.chinenual.com/api/v1/version?latest&app=Synergize&v=2.6.1&OS=darwin&ARCH=amd64&OSVER=23.4.0
2024/06/15 15:30:19 INFO: astikit: worker is now waiting...
2024/06/15 15:30:19 INFO: Latest version is v2.6.1
2024/06/15 15:31:46 INFO: ZEROCONF: found Synergia via state: localhost:59437 (Synergia (App))
2024/06/15 15:31:46 INFO: ZEROCONF: zero or more than one VST: []zeroconf.Service{zeroconf.Service{InstanceName:"Synergia (App)", HostName:"localhost", Port:0xe82d, Text:map[string]string(nil)}}
2024/06/15 15:31:46 INFO: ZEROCONF: GetSynergyConfig success: [2]struct { HasDevice bool; AlreadyConfigured bool; Name string; Choices *[]zeroconf.Service }{struct { HasDevice bool; AlreadyConfigured bool; Name string; Choices *[]zeroconf.Service }{HasDevice:true, AlreadyConfigured:false, Name:"", Choices:(*[]zeroconf.Service)(0xc0001494e8)}, struct { HasDevice bool; AlreadyConfigured bool; Name string; Choices *[]zeroconf.Service }{HasDevice:false, AlreadyConfigured:false, Name:"", Choices:(*[]zeroconf.Service)(nil)}}
2024/06/15 15:31:53 INFO: ZEROCONF: config Synergy selected by user: zeroconf.Service{InstanceName:"Synergia (App)", HostName:"localhost", Port:0xe82d, Text:map[string]string(nil)}
2024/06/15 15:31:53 WARN: overriding VST hostname (localhost) to localhost for Synergia (App)
2024/06/15 15:31:53 INFO:  --> socket.Open(localhost:59437)
2024/06/15 15:31:53 INFO: Connected to Synergy Synergia (App)
2024/06/15 15:31:53 INFO: url: https://api.chinenual.com/api/v1/version?latest&app=Synergize&v=2.6.1&OS=darwin&ARCH=amd64&OSVER=&synergy=vst&cs=false
2024/06/15 15:31:54 INFO: Latest version is v2.6.1
2024/06/15 15:33:19 INFO: Add vce /Users/ty/Documents/Synergize/SynergyVoiceLibrary/VOICES/Internal/CATHERG.VCE to CRT at slot 2

![image](https://github.com/chinenual/synergize/assets/55908042/6ab713d9-9a7a-4517-b470-e36d55521f46)

**Comment by chinenual** [comment]
Thanks for the excellent bug report - I've been able to reproduce.  Hopefully can diagnose and fix soon.
