### ISSUE TITLE
Provide option to suppress Info and Confirm prompts

### ISSUE THREAD

**Issue by tyhodson** [chinenual/synergize#83]
Enhancement request to provide an option in Settings to suppress Info and Confirm prompts. These are super helpful and reassuring while learning the interface, but now that I'm more familiar with it I'm ready to move faster. 

For example, when leaving Voice mode, I have to respond to a prompt asking if I'm sure, and then a second prompt that informs me that it has been done.

Thanks for considering!

**Comment by chinenual** [comment]
Partly fixed for 2.6.2.    Info dialogs now auto expire after 3 seconds, so you don't have to acknowledge them.  I've left the Confirm prompts as is since they warn against losing data/pending edits.

**Comment by tyhodson** [comment]
A reasonable compromise — thanks!
